OPENAI_API_KEY = "sk-proj-dGwtIVYP1BQ1yZrXYPeCT3BlbkFJozxIGb9tE6anY342NfTf"
CRAWLER_URLS = ["https://blubank.sb24.ir/about", "https://blubank.sb24.ir/commercial-coperation", "https://blubank.sb24.ir/faq/", "https://digiato.com/training/how-to-take-bluebank-loans"]

[postgres]
host = "localhost"
port = "5433"
user = "postgres"
password = "comeng2002"
dbname = "finaldb"