OPENAI_API_KEY = "sk-****"
CRAWLER_URLS = ["https://blubank.sb24.ir/about", "https://blubank.sb24.ir/commercial-coperation", "https://blubank.sb24.ir/", "https://digiato.com/training/how-to-take-bluebank-loans"]